name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libolm-dev

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Build binary
        run: |
          mkdir build
          ./build.sh -o build/matrix-pylon-${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: matrix-pylon-${{ matrix.arch }}
          path: build/matrix-pylon-${{ matrix.arch }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: "build/*"
          tag_name: ${{ github.ref_name }}
